# Generated by Django 6.0.5 on 2026-05-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorapplication',
            name='government_id',
            field=models.FileField(upload_to='applications/ids/'),
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='medical_certificate',
            field=models.FileField(upload_to='applications/certs/'),
        ),
    ]
