# Generated by Django 6.0.5 on 2026-05-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
