# Generated by Django 6.0.5 on 2026-05-28 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorprofile_location'),
        ('donors', '0004_notification'),
    ]

    operations = [
    ]
