# Generated by Django 6.0.5 on 2026-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_merge_0002_donorprofile_location_0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('request', 'Donation Request'), ('accepted', 'Request Accepted'), ('request_approved', 'Request Approved by Admin'), ('request_rejected', 'Request Rejected by Admin')], max_length=20),
        ),
    ]
