# Generated by Django 6.0.5 on 2026-05-31 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_notification_notif_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorapplication',
            name='government_id',
        ),
    ]
