# Generated by Django 6.0.5 on 2026-05-31 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_remove_donorapplication_government_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='donor/ids/'),
        ),
    ]
