# Generated by Django 6.0.5 on 2026-05-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_donorprofile_government_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorapplication',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='applications/ids/'),
        ),
    ]
