# Generated by Django 6.0.5 on 2026-05-31 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0009_donorapplication_government_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_blood_type_locked',
            field=models.BooleanField(default=False),
        ),
    ]
