# Generated by Django 6.0.5 on 2026-05-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0010_donorprofile_is_blood_type_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorapplication',
            name='is_id_recheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='id_recheck_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='applications/certs/'),
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('id_recheck', 'ID Re-check')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('request', 'Donation Request'), ('accepted', 'Request Accepted'), ('request_approved', 'Request Approved by Admin'), ('request_rejected', 'Request Rejected by Admin'), ('id_recheck_approved', 'ID Re-check Approved'), ('id_recheck_rejected', 'ID Re-check Rejected')], max_length=25),
        ),
    ]
