# Generated by Django 6.0.5 on 2026-05-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_donorapplication_is_id_recheck_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorapplication',
            name='is_id_recheck',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='id_recheck_pending',
        ),
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_blood_type_locked',
        ),
        migrations.AddField(
            model_name='donorapplication',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verification_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donorprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('request', 'Donation Request'), ('accepted', 'Request Accepted'), ('request_approved', 'Request Approved by Admin'), ('request_rejected', 'Request Rejected by Admin')], max_length=25),
        ),
    ]
