# Generated by Django 6.0.5 on 2026-05-31 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0012_remove_donorapplication_is_id_recheck_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('unverified', 'Unverified')], default='pending', max_length=15),
        ),
    ]
