# Generated by Django 6.0.5 on 2026-06-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0013_alter_donorapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_blood_type_locked',
            field=models.BooleanField(default=False),
        ),
    ]
