# Generated by Django 6.0.5 on 2026-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0014_donorprofile_blood_type_locked'),
        ('donors', '0014_donorprofile_is_blood_type_locked'),
    ]

    operations = [
    ]
