# Generated by Django 6.0.5 on 2026-06-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0015_merge_20260601_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationlog',
            name='proof_document',
            field=models.FileField(blank=True, null=True, upload_to='donations/proofs/'),
        ),
    ]
