# Generated by Django 6.0.5 on 2026-06-01 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0016_donationlog_proof_document'),
        ('donors', '0016_notification_link'),
    ]

    operations = [
    ]
