# Generated by Django 6.0.5 on 2026-06-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0017_merge_20260601_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationlog',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='donationlog',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationlog',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donationlog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
