# Generated by Django 6.0.5 on 2026-06-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_donationlog_admin_notes_donationlog_is_rejected_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='is_blood_type_locked',
        ),
    ]
