# Generated by Django 6.0.5 on 2026-06-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0018_donationlog_admin_notes_donationlog_is_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('approved', 'Application Approved'), ('rejected', 'Application Rejected'), ('request', 'Donation Request'), ('accepted', 'Request Accepted'), ('log_verified', 'Donation Log Verified'), ('log_rejected', 'Donation Log Rejected')], max_length=25),
        ),
    ]
