# Generated by Django 6.0.5 on 2026-06-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0019_alter_notification_notif_type'),
        ('donors', '0019_remove_donorprofile_is_blood_type_locked'),
    ]

    operations = [
    ]
