# Generated by Django 6.0.5 on 2026-05-30 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='requests/certs/'),
        ),
    ]
