# Generated by Django 6.0.5 on 2026-05-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0003_recipientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('pending_admin', 'Pending Admin Review'), ('pending', 'Pending Donor Response'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('rejected_by_admin', 'Rejected by Admin')], default='pending_admin', max_length=20),
        ),
    ]
