# Generated by Django 6.0.5 on 2026-05-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0004_bloodrequest_admin_notes_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
