# Generated by Django 6.0.5 on 2026-05-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0005_recipientprofile_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipientprofile',
            name='blood_type',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5),
        ),
    ]
