# Generated by Django 6.0.5 on 2026-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0006_alter_recipientprofile_blood_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='urgency',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='blood_bags',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='needed_by_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
