# Generated by Django 6.0.5 on 2026-05-31 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0006_alter_recipientprofile_blood_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='donor_government_id',
            field=models.FileField(blank=True, null=True, upload_to='requests/donor_ids/'),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='recipient_government_id',
            field=models.FileField(blank=True, null=True, upload_to='requests/recipient_ids/'),
        ),
    ]
