# Generated by Django 6.0.5 on 2026-05-31 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0007_bloodrequest_donor_government_id_and_more'),
        ('recipients', '0007_remove_bloodrequest_urgency_bloodrequest_blood_bags_and_more'),
    ]

    operations = [
    ]
