# Generated by Django 6.0.5 on 2026-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipients', '0009_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipientprofile',
            name='blood_type_locked',
            field=models.BooleanField(default=False),
        ),
    ]
