# Generated by Django 6.0.5 on 2026-05-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_role',
            field=models.CharField(choices=[('donor', 'Donor'), ('recipient', 'Recipient'), ('admin', 'Admin')], default='recipient', max_length=10),
        ),
    ]
