# Generated by Django 6.0.5 on 2026-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
