# Generated by Django 6.0.5 on 2026-05-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='government_id',
            field=models.FileField(blank=True, null=True, upload_to='recipient/ids/'),
        ),
    ]
