# Generated by Django 6.0.5 on 2026-05-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_government_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='government_id',
        ),
    ]
