# Generated by Django 6.0.5 on 2026-06-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_government_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='flag_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='flagged_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
